name: Deploy Go Application

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t dhruvnakum/anonymous-go .
      - name: Push image to docker hub
        run: docker push dhruvnakum/anonymous-go:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull dhruvnakum/anonymous-go:latest
      - name: Delete old container
        run: docker rm -f go-app-container  
      - name: Run docker container          
        run: docker run -d -p 3000:3000 --name anonymous-go dhruvnakum/anonymous-go